### ISSUE TITLE
Append Instead of Overwrite

### ISSUE THREAD

**Issue by ghost** [Essent/nativescript-custom-entitlements#1]
When I wrote the original code, I made it overwrite build.xcconfig instead of checking if CODE_SIGN_ENTITLEMENT exists and appending only if that check was false.

As it stands, it will erase any other pre-existing values in build.xcconfig, so you want to update this, otherwise things like nativescript-cli's DEVELOPMENT_TEAM_ID can't be set there.

**Comment by spike1292** [comment]
Tnx for your suggestion!
implemented with append 😉
https://github.com/Essent/nativescript-custom-entitlements/blob/master/lib/before-prepare.js#L14.

**Comment by ghost** [comment]
@spike1292 Make sure to check the file for "CODE_SIGN_ENTITLEMENTS" before appending, otherwise you will have a bunch of duplicate lines because of multiple prepares,

Or it might also overwrite an existing manually entered CODE_SIGN_ENTITLEMENTS=..., which can be avoided also with this text check (:

**Comment by spike1292** [comment]
merged #2 which adds the check
