### ISSUE TITLE
Prepare Fails if build.xcconfig doesn't already exist

### ISSUE THREAD

**Issue by ghost** [Essent/nativescript-custom-entitlements#3]
@spike1292 It seems that the plugin expects build.xcconfig to exist, if it doesn't, `tns prepare` fails with no error message

**Comment by spike1292** [comment]
@vbresults you are correct, will try to fix it this week

**Comment by spike1292** [comment]
@vbresults just published version 0.2.0, 
implemented fs-promise to make error handling easier. 
see commit 119cf67fb70b3a65becb649d91a61910d71d18da

Let me know what you think!
